# Generated by Django 5.2.8 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
